name: currency_converter_app
description: A simple Flutter app for currency conversion.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Application version
version: 1.0.0+1

# Dart SDK environment
environment:
  sdk: '>=2.17.0 <3.0.0' # Ensure this matches the Dart SDK you are using

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6 # Required for HTTP requests
  cupertino_icons: ^1.0.8 # For iOS styled icons
  flutter_dotenv: ^5.0.2

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configuration
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/dollar.png
    - assets/images/euro.png

  # Fonts (if needed in the app, leave this section for future extension)
  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: fonts/OpenSans-Regular.ttf
  #       - asset: fonts/OpenSans-Bold.ttf
  #         weight: 700
